### PR TITLE
switch bit layout of DnaString to match Kmers -- makes get_kmer() fas…

### PR DESCRIPTION
**Pull request by pmarks**
…ter. Add some inline directives

### CODE REVIEW

**Comment by DavidBJaffe** [comment]
Can you please merge dj/add_k12 into this branch? If you do that I will test performance.

**Comment by pmarks** [comment]
@DavidBJaffe ok, I merged the K12 stuff. FYI - if you have any file written to disk with write_obj (serde), that contains a DnaString, it will need to be re-generated.

**Comment by DavidBJaffe** [comment]
I seem to observe a change in results.  I think this is from a clean start (no dependence on serde-written objects).  I will isolate the apparent difference.  It might be a mistake in my analysis.

**Comment by DavidBJaffe** [comment]
It looks like the meaning of less than for DnaStrings was changed.  Now it appears to be lexicographical.  Before it was something else.  So that changed my results.  But I'm not 
yet sure that that explains the full extent of the observed differences.

**Comment by DavidBJaffe** [comment]
The new code is faster and has a more natural sort order.  That's all I see that's different so LGTM!

**Pull request merged**
